### PR TITLE
Refactor - Home Page Sections

### PR DESCRIPTION
**Pull request by bharati-21**
- Edited home page section
  - Removed previous categories in section categories, and added genres as categories
  - Added top picks categories

### CODE REVIEW

**Review by AtulHande03a — APPROVED** [review]
looks good

**Comment by bharati-21** [comment]
> looks good

Thank you!

**Review by NeerajVodala — APPROVED** [review]
Looks good to me.
All the best.

**Review by sagargse — APPROVED** [review]
looks good to me

**Comment by bharati-21** [comment]
> Looks good to me. All the best.

Thank you! 👍🏽

**Comment by bharati-21** [comment]
> looks good to me

Thank you!

**Review by chanchal16 — COMMENTED** [review]
One suggestion, at some places you have given classname as .section__ and at some places .section --. So try to stick on either one of them. 
Overall looks good to me!

**Pull request merged**
