### PR TITLE
Products Page

### PR DESCRIPTION
**Pull request by bharati-21**
- Created filters and product catalog section
- The filter categories include- 
   - product categories
   - price
   - rating
   - book genres
   - book cover type

- Added product cards with a wishlist button, add to cart button, product image, product title, subtitle, product discounted price, discount percentage, and the original price.

PREVIEW
image

### CODE REVIEW

**Review by zabihshaik — APPROVED** [review]
Everything looks good to merge.
Appreciate the Folder Structure and the Code Structure. UI looks clean.

**Review by nyyshaaa — APPROVED** [review]
Nice ui, clean design. You can merge.

**Comment by bharati-21** [comment]
> Everything looks good to merge. Appreciate the Folder Structure and the Code Structure. UI looks clean.

Thank you!

**Comment by bharati-21** [comment]
> Nice ui, clean design. You can merge.

Thank you!

**Pull request merged**
