### PR TITLE
Authentication pages

### PR DESCRIPTION
**Pull request by bharati-21**
Created auth page -login and sign-up page structure and style.
- Login page contains:
  - email input textbox
  - password input textbox
  - login button
  - Forgot password button link
  - A sign up page button link

- Signup page contains
  - first and last name input
  - email input
  - password and confirm password input
  - Sign up button
  - Forgot password button link
  - A sign up page button link

### CODE REVIEW

**Review by poojavishnoi — APPROVED** [review]
Looks very nice.
Also very well structured code.
Good to merge.

**Review by rishmi5h — APPROVED** [review]
UI looks 👌
good to merge

**Comment by bharati-21** [comment]
> Looks very nice. Also very well structured code. Good to merge.

Thank you!

**Comment by bharati-21** [comment]
> UI looks 👌 good to merge

Thank you!

**Pull request merged**
